# Default values for registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: reg.k8s.home

persistence:
  enabled: true
  size: 5G
  storageClass: local-path

