######################################################################################
# System packages
######################################################################################

- name: "Install system packages"
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

######################################################################################
# Docker Repo
######################################################################################

- name: "Add Dockers official GPG key"
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Set up the stable docker repository"
  become: true
  apt_repository:
    repo: "{{ DOCKER_REPO }}"
    state: present
    filename: docker
    update_cache: yes

######################################################################################
# Install Docker
######################################################################################

- name: "Remove preinstalled"
  become: true
  package:
    name: 
      - docker 
      - docker-engine
      - docker.io 
      - containerd 
      - runc
    state: absent

- name: "Install docker"
  become: true
  apt: 
    name: 
      - docker-ce={{ DOCKER_VERSION }} 
      - containerd.io
    state: present

- name: "Fix docker page"
  become: true
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: "Add user to docker group"
  become: true
  user:
    name: "{{ DOCKER_USER }}"
    groups: docker
    append: yes

- name: Copy daemon.json to enable self hosted registry
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  tags:
    - docker-copy-daemon-json
